elastic-query-service:
  backPressure-delay-ms: 500


server:
  port: 8183


elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter
  connection-url: https://nxslz9rfgm:ii34zb0h9v@kafka-6066187317.us-east-1.bonsaisearch.net:443
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  user: nxslz9rfgm
  pass: ii34zb0h9v

user-config:
  username: test
  password: 1234
  roles: USER

spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 125MB
  data:
    elasticsearch:
      client:
        reactive:
          max-in-memory-size: 125MB
