elastic-query-service:
  backPressure-delay-ms: 500

kafka-config:
  bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-partitions: 3
  replication-factor: 3
  sleep-time-ms: 1000
  max-interval-ms: 10000
  retry-multiplier: 2.0
  admin-retry-max: 1

server:
  port: 8183


elastic-query-config:
  text-field: text

elastic-config:
  index-name: twitter-index
  connection-url: https://tamin-search-6751797221.eu-central-1.bonsaisearch.net:443
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
  user: c7k18527yx
  pass: 2ba3dvtsh8

user-config:
  username: test
  password: 1234
  roles: USER

spring:
  webflux:
    base-path: /reactive-elastic-query-service
  codec:
    max-in-memory-size: 25MB
  data:
    elasticsearch:
      client:
        reactive:
          max-in-memory-size: 25MB